name: CI/CD Pipeline

on:
  push:
    branches: [ main, development, family ]
  pull_request:
    branches: [ main, development, family ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      FLASK_APP: app.py
      FLASK_ENV: testing
      SECRET_KEY: github-actions-test-key
      DATABASE_URL: sqlite:///:memory:
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create instance directory
      run: |
        mkdir -p instance
    - name: Run tests
      run: |
        python -m pytest -v --cov=app tests/

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run linting
      run: |
        flake8 . --count --max-complexity=15 --max-line-length=150 --statistics --extend-ignore=E226,E302,E41,E722,W293,F401 --exclude=tests/*,venv/*,.git/*,__pycache__/*,migrations/*

  deploy-family:
    needs: [test, lint]
    if: github.ref == 'refs/heads/family' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Deploy to family environment
      env:
        FLASK_APP: app.py
        FLASK_ENV: production
      run: |
        echo "Deploying to family environment..."
        # Add deployment steps here
